server:
  port: 8083

logging:
  level:
    org.springframework.web: INFO

spring:
  application:
    name: ariss-barrier
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ariss_barrier
        use_sql_comments: true
        format_sql: true
        criteria:
          literal_handling_mode: BIND
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_MAIN_DSN:jdbc:postgresql://localhost:5432/unit_techno?currentSchema=ariss_barrier}
    username: ${DATASOURCE_MAIN_USERNAME:ariss_barrier_admin}
    password: ${DATASOURCE_MAIN_PASSWORD:squd}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

event:
  type:
    7777:
      info: "административный корпус"
      entryType: OUT
    8888:
      info: "задний проход"
      entryType: IN